name: Deploy AppRunner Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate CloudFormation Template
        run: aws cloudformation validate-template --template-body file://cloudformation/template.yml

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.yml \
            --stack-name DevSecOpsAppRunnerStack \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --parameter-overrides \
              CodeBucket=my-app-bucket-name \
              CodeKey=app.zip

      - name: Get App Runner Service URL
        run: |
          aws cloudformation describe-stacks \
            --stack-name DevSecOpsAppRunnerStack \
            --query "Stacks[0].Outputs[?OutputKey=='ServiceUrl'].OutputValue" \
            --output text
