name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-scan-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      S3_KEY: app.zip
      STACK_NAME: DevSecOpsAppRunnerStack

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run tests
        run: npm test
        working-directory: ./app

      - name: Install zip utility
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build app zip
        run: |
          pwd
          ls -la
          zip -r ../app.zip .
          ls -la ../

      - name: Verify app.zip exists
        run: ls -la ../app.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload app.zip to S3
        run: aws s3 cp ../app.zip s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }}

      - name: Deploy CloudFormation stack
        id: deploy-stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.yml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }} \
            --parameter-overrides \
              CodeBucket=${{ env.S3_BUCKET }} \
              CodeKey=${{ env.S3_KEY }}

      - name: Get API URL from CloudFormation outputs
        id: get-api-url
        run: |
          API_URL=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
          echo "API_URL=$API_URL" >> $GITHUB_ENV

      - name: Run OWASP ZAP Scan
        run: bash ./scripts/zap-scan.sh ${{ env.API_URL }} --skip-zap